services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true

    volumes:
      - ~/data-minecraft-server/data-1.20.4-forge:/data # directory to persist your world state :)

    ports:
      # ports required for gameplay
      - "25565:25565" # tcp port used by java clients
    
    environment:
      # required setup
      EULA: "TRUE"
      VERSION: "1.20.4"

      # system resources
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"

      # mods sourced from https://modrinth.com/mods
      TYPE: "NEOFORGE"
      MODRINTH_PROJECTS: "terralith,tectonic,towns-and-towers,architectury,building-wands,builders-delight,exlines-furniture,more-mob-variants,collective,double-doors,natures-compass,better-archeology"
      # unstable: balm,waystones
      # unsupported: mob-catalog,bens-sharks

    env_file:
      # set your optional settings in the env file if desired
      - path: .env
        required: false
