services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true

    volumes:
      - ~/data-minecraft-server/data-1.20.4-neoforge:/data # directory to persist your world state :)

    ports:
      # ports required for gameplay
      - "25565:25565" # tcp port used by java clients
    
    environment:
      # required setup
      EULA: "TRUE"
      VERSION: "1.20.4"

      # mods sourced from https://modrinth.com/mods
      TYPE: "NEOFORGE"
      MODRINTH_PROJECTS: "builders-delight,structure-gel-api,terrablender,glitchcore,biomes-o-plenty,ct-overhaul-village,exlines-furniture,dungeons-plus,more-mob-variants,collective,double-doors,natures-compass"
      # unstable: balm,waystones
      # unsupported: mob-catalog,bens-sharks

    env_file:
      # set your optional settings in the env file if desired
      - path: .env
        required: false
